var kata_bijak=new Array()
kata_bijak[0]="Seseorang yang luar biasa itu sederhana dalam ucapannya, Tetapi hebat dalam tindakanya --Sherlock Holmes--";
kata_bijak[1]="Suatu hal yang patut menjadi kebanggaan adalah ketika seseorang memutuskan untuk menjadi dirinya sendiri. --Sherlock Holmes--";
kata_bijak[2]="Agar masa depanmu lebih baik maka berusahalah mulai dari sekarang. --Sherlock Holmes--";
kata_bijak[3]="Masa depan bukanlah tujuan utama, melainkan perbaikan melalui tindakan yang benar – benar nyata.";
kata_bijak[4]="Kamu harus mengetahui tujuan utama masa depanmu, agar kamu tahu sepenuhnya tujuan hidupmu.";
kata_bijak[5]="Merupakan suatu hal yang sangat sukar ketika semua yang awalnya baik tiba - tiba berubah menjadi buruk. Dan yang lebih sukar dari itu adalah memilih sebuah pilihan antara melepaskan atau tetap bertahan.";
kata_bijak[6]="Ketika kamu bermimpi, jagan pernah takut untuk bermimpi setinggi – tingginya, karena ketka Tuhan berkehendak engkau bermimpi setinggi – tingginya, berarti Dia pun berkehendak bahwa kamu bisa mewujudkannya.";
kata_bijak[7]="Teruslah percaya dan bekerja keraslah";
kata_bijak[8]="Jika bisa menjadi sukses sewaktu muda, kenapa harus menunggu usia tua?";
kata_bijak[9]="Kurang pandai mungkin bisa di perbaiki, tapi kejujuran tidak akan pernah mudah untuk di tanamkan";
kata_bijak[10]="Jangan hanya memandang dari salah satu sisi, agar pandanganmu tidak tersempitkan";
kata_bijak[11]="Jauhilah orang yang banyak berfikir negative karena dari sana akan muncul masalah dari sebuah solusi yang ada";
kata_bijak[12]="Dengan bekerja keras engkau akan mengalahkan orang – orang yang berbakat";
kata_bijak[13]="Ketika kamu memiliki keyakinan untuk mampu melakukan maka kamu akan bisa mewujudkan segala mimpimu";
kata_bijak[14]="Orang yang bertindak tanpa berpikir adalah orang yang gagal";
kata_bijak[15]="Gagal adalah masalah kecil namun putus asa adalah masalah yang besar";
kata_bijak[16]="Sebuah langkah kecil adalah sebuah awal jalan yang panjang";
kata_bijak[17]="Tekuni salah satu bidang maka Anda akan menjadi orang hebat yang berhasil";
kata_bijak[18]="harapan dan keinginan ini semestinya sejalan, yah sejalan dengan seberapa besar usaha ia dalam mewujudkannya";
kata_bijak[19]="Seorang juara pasti akan percaya pada dirinya sendiri, walaupun tidak ada orang yang mau mempercayainya lagi";
kata_bijak[20]="Ketakutan harus dikerdilkan, karena ketakutan adalah musuh besar impian yang akan diwujudkan";
kata_bijak[21]="Kerja keras orang tua itu karena ingin anak – anaknya menjadi pribadi yang bukan hanya biasa tapi luar biasa";
kata_bijak[22]="Saat orang lain disekitarmu berkata bahwa dirimu telah berubah, sebenarnya hanyalah engkau mulai berhenti untuk tidak melakukan hal – hal yang sperti biasanya mereka ingin Anda melakukannya.";
kata_bijak[23]="Agar langkah sukses Ada 10 kali lebih cepat, maka Anda perlu mempunyai keberanian untuk mengambil keputusan.";
kata_bijak[24]="Kesuksesan akan sangat jauh, apabila Anda bayak melakukan hal – hal yang sia – sia.";
kata_bijak[25]="Sebuah keputusan yang paling baik ialah dengan berpedoman pengalaman hidup. Dan pengalaman hidup diperoleh dari keputusan yang pernah salah";
kata_bijak[26]="Setiap hari sangatlah berharga, janganlah menunggu waktu yang tepat untuk mulai melangkah.";
kata_bijak[27]="Sebuah keberuntunga akn datang ketika Anda dapat mengambil peluang dan kesempatan dengan persiapan yang matang";
kata_bijak[28]="Sikap Anda saat ini adalah bentuk dari pengalaman hidup Anda";
kata_bijak[29]="Waktu sangatlah berharga, janganlah pernah menyia – nyiakannya";
kata_bijak[30]="Waktu itu ibarat pedang yang bila digunakan dengan baik akan membwamu pada sebuah keberuntungan dan sebaliknya jika engkau lalai akan membunuhmu.";
kata_bijak[31]="Teruslah optimis dan berpikir positif dalam hidupmu.";
kata_bijak[32]="Ketika ada sebuah keinginan yang muncul untuk memulai suatu hal yang sudah di targetkan, maka harus muncul sebuah keberanian untuk menyelesaikannya.";
kata_bijak[33]="Jangan menunda untuk lekas berusaha demi keindahan masa depanmu";

var acak=Math.floor(33*Math.random());
document.write("<i>");
document.write(kata_bijak[acak]);
document.write("</i>");